---
title: "dm_abundance"
date: "20 January 2026"
output: html_document
author: "Elizabeth Daigle"
---
# Read in packages, functions, and directories
```{r}
source(paste0(here::here(), "/1-Config/config.R"))
```

# Read in sample metadata
```{r}
meta <- read_tsv(paste0(configDir, "/sampleReadList.txt"))
```

# final samples to be included in analyses
```{r}
samples_drop=c('D17_2', 'P17_1', 'O5_1', 'O15_1', 'N17_1', 'M4_2', 'M20_2', 'M19_1', 'M16_2', 'K1_1', 'K21_2', 'K19_2', 'K17_2', 'K11_1', 'J7_2', 'J1_2', 'J17_1', 'I13_1', 'H5_2', 'H13_2', 'F5_2', 'F23_2', 'F21_2', 'F1_2', 'E7_1', 'E21_1', 'E18_2', 'E16_2', 'E12_2', 'E10_2', 'D5_2', 'D19_1', 'D11_2', 'C3_1', 'C1_1', 'B15_1', 'A23_1', 'A21_1', 'A13_2', 'A14_2', 'K23_2')

samples_used <- meta %>%
  filter(!samplename %in% samples_drop) %>%
  filter(!Type=="Saliva") %>%
  filter(!Subject %in% c("Control_1", "Control_2")) %>%
  filter(!Set %in% c(1,6,7,8,9,10,11,12,13)) %>%
  # remove 7 samples that were resequenced (subject 4,    subject 3)
  #keep sample with more mapped reads
  filter(!samplename %in% c("O17_1", "O19_1", "O21_1", "L23_1",     "K23_1", "M15_1", "M23_1"))

n_samples_total <- samples_used %>%
  # find the number of genes in each sample and the sum of their RPKGs
  group_by(Type) %>%
  summarize(n_samples=n_distinct(samplename))
sum((n_samples_total %>% filter(str_detect(Type, "Capsule")))$n_samples)

saveRDS(n_samples_total, file = paste0(dataDir, "/number_samples_type.rds"))
```


# Read in dsrAB gene counts
```{r}
# capsule data
capsule <- read_tsv(paste0(abundanceDir, "/Capsule/concat_dsrAB_Capsule_Abundances_RPKG_redo.txt"))
# stool data
stool <- read_tsv(paste0(abundanceDir, "/Stool/concat_dsrAB_Stool_Abundances_RPKG_redo.txt"))
# combine capsule and stool data
samples <- bind_rows(capsule, stool) %>%
  mutate(subject=as.numeric(str_extract(.$coassembly, "\\d+")))
```

```{r}
#which hits are dups?
# want to make sure they all get filtered out since they have NA for distance
closest_ref_no_2018 <- read_csv(paste0(dataDir, "closestRefInfo_allScoreThresholdHits_wSingleClosestRef_no_2018_capsule.csv")) 
dups <- closest_ref_no_2018 %>%
  filter(is.na(distance)) %>%
  # agree that all but two are duplicates (they have another hit to the same gene)
# Stool_14 220955_5 and Capsule_14 148417_5 should be added back in because they were marked as duplicates for genes in different coassemblies!
  filter(!str_detect(hit_id, "Stool_14.k141_220955_5/63-175|Capsule_14.k141_148417_5/63-175"))

samples_no_dups <- samples %>%
  filter(!geneLoc %in% dups$hit_id)
```

```{r}
# filter and remove duplicate genes
samples_unique_genes <- samples_no_dups %>%
  # ED update 10/4/26: actually keep RPKG of zero so we can see which samples did not have reads matching the coassembly hits
  # Remove RPKGs of 0 (feature counts keeps genes even when nothing has mapped to them) 
  #filter(RPKG>0) %>%
# make subject a factor
  mutate(subject = factor(subject)) %>%
# add capsule type (1,2,3,4, most proximal to most distal)
  left_join(meta %>% select(samplename, Type, Set), 
            by = c("sample" = "samplename")) %>%
  #remove practice capsules found in subject 1 and others
  filter(!Set %in% c(1,6,7,8,9,10,11,12,13)) %>%
  # remove 7 samples that were resequenced (subject 4,    subject 3)
  #keep sample with more mapped reads
  filter(!sample %in% c("O17_1", "O19_1", "O21_1", "L23_1",     "K23_1", "M15_1", "M23_1")) %>%
# filter for unique genes in each sample
# want to keep gene domain with the highest score, if there is a tie return just the first hit encountered
  group_by(geneID, sample) %>%
  slice_max(Score, n = 1, with_ties = FALSE) %>%
  ungroup()

samples_in_coassemblies_no_hits <- meta %>% 
  filter(samplename %in% setdiff(unique(samples_used$samplename), unique(samples_unique_genes$sample)))
# these are the samples that are from coassemblies with no hits (which are not the same as samples from coassemblies with hits but no reads mapping in the individual sample)
```

# Add a column to samples that has the single_closest_ref
```{r}
samples_unique_genes_with_names_no_2018 <- samples_unique_genes %>% filter(geneLoc %in% closest_ref_no_2018$hit_id) %>%
  left_join(closest_ref_no_2018 %>% select(hit_id, single_closest_ref, distance),
            by = c("geneLoc" = "hit_id")) %>% 
  mutate(sample_type = ifelse(grepl("Stool", coassembly), "Stool", "Capsule"))

saveRDS(samples_unique_genes_with_names_no_2018, file = paste0(dataDir, "/samples_unique_genes_with_names_no_2018.rds"))
```

## for the asr genes 
```{r}
asr <- read_tsv(paste0(abundanceDirASR, "/concat_asrABC_Abundances_RPKG_redo.txt")) %>%
  mutate(subject=as.numeric(str_extract(.$coassembly, "\\d+")))  %>% 
  mutate(sample_type = ifelse(grepl("Stool", coassembly), "Stool", "Capsule"))

# filter and remove duplicate genes
asr_unique_cluster <- asr %>%
  # ED update 10/4/26: actually keep RPKG of zero so we can see which samples did not have reads matching the coassembly hits
  # Remove RPKGs of 0 (feature counts keeps genes even when nothing has mapped to them) 
  #filter(RPKG>0) %>%
  mutate(subject = factor(subject)) %>%
# add capsule type
  left_join(meta %>% select(samplename, Type, Set), 
            by = c("sample" = "samplename")) %>%
  #remove practice capsules found in subject 1
  filter(!Set %in% c(1,6,7,8,9,10,11,12,13)) %>%
  # remove 7 samples that were resequenced (subject 4,    subject 3)
  #keep sample with more mapped reads
  filter(!sample %in% c("O17_1", "O19_1", "O21_1", "L23_1",     "K23_1", "M15_1", "M23_1")) %>%
# filter for unique genes in each sample
# want to keep gene domain with the highest score, if there is a tie return just the first hit encountered
  group_by(geneID, sample) %>%
  slice_max(Score, n = 1, with_ties = FALSE) %>%
  ungroup() 

# filtering by geneID leaves different genes with the same geneNum/locations, and you end up with more than 3 hits for each contig

saveRDS(asr_unique_cluster, file = paste0(dataDir, "/asr_unique_cluster.rds"))
```



