---
title: "asrABC Capscan Analysis"
date: "23 December 2025"
author: "Elizabeth Daigle"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Read in packages and functions
```{r}
source(paste0(here::here(), "/1-Config/config.R"))
```

# read in unique dsr clusters
```{r}
dsr_unique <- readRDS(paste0(dataDir, "/samples_unique_genes_with_names_no_2018.rds"))
```

```{r}
asr_unique <- readRDS(paste0(dataDir, "/asr_unique_cluster.rds"))
```

# Making color palettes for plots
```{r}
# Generate a viridis palette with 20 colors
viridis_palette <- viridis(20)
viridis_palette

boxplot_colors <- c(viridis_palette[6], viridis_palette[16])
gene_colors <- c("#D98E21", "#6B8E23")
sample_type_colors <- c("#AA3377", "#6F7042")
sample_type_colors_2 <- c("#1E88E5", "#6F7042")

jitter_colors <- c("#4477AA", "#59A075", "#AA3377", "#DDAA33", "#6F7042")
```

# get summary statistics for Figure 6A
```{r}
unique_hits_summary_dsr <- dsr_unique %>%
  filter(single_closest_ref != "Moorella_thermoacetica_Y72_copy_2__MooTher5") %>%
  # need to remove this partial gene because it was removed to make the other abundance figures and when it is removed, one sample is no longer in the df. This way, both the abundance figures and the asr/dsr figures will have 146 samples included in the analysis
  filter(!geneNum == "Stool_14.k141_240693_1") %>%
  # find unique contigs in each coassembly
  # don't care about how we are selecting a subunit here since we just want overall count. RPKG will be in figure part b
  group_by(subject, contig, sample_type) %>%
  slice_max(RPKG, n = 1, with_ties = FALSE) %>%
  ungroup %>%
  # find how many contigs are in each capsule type and stool
  group_by(subject, sample_type) %>%
  summarize(number_hits=n()) %>%
  group_by(sample_type) %>%
  # add up all the hits found in each subject for a given Type. take the median and find IQR
  summarize(n_hits_total=sum(number_hits), median_hits=median(number_hits), q_25=quantile(number_hits, probs=0.25), q_75=quantile(number_hits, probs=0.75)) %>%
  mutate(hits_per_subj = paste0(median_hits, " [IQR ", q_25, "-", q_75, "]")) %>%
  select(sample_type, n_hits_total, hits_per_subj)

unique_hits_summary_asr <- asr_unique %>%
  group_by(subject, contig, sample_type) %>%
  slice_max(RPKG, n = 1, with_ties = FALSE) %>%
  ungroup %>%
  group_by(subject, sample_type) %>%
  summarize(number_hits=n()) %>%
  group_by(sample_type) %>%
  summarize(n_hits_total=sum(number_hits), median_hits=median(number_hits), q_25=quantile(number_hits, probs=0.25), q_75=quantile(number_hits, probs=0.75)) %>%
  mutate(hits_per_subj = paste0(median_hits, " [IQR ", q_25, "-", q_75, "]")) %>%
  select(sample_type, n_hits_total, hits_per_subj)

## for these, the dsr hits get filtered by dups, etc. 
figure_6a <- unique_hits_summary_dsr %>% left_join(., unique_hits_summary_asr, by = "sample_type", suffix = c("_dsr", "_asr"))
```

# How do RPKGs compare to the dsrAB genes? 
# Cannot plot total RPKG since asrABC protein has 3 subunits while dsrAB has 2.
# Using median to account for this
```{r}
# Get median RPKG across contigs in each sample
# then find the sum of RPKG in a sample
plot_RPKG_dsr_median <- dsr_unique %>%
  filter(single_closest_ref != "Moorella_thermoacetica_Y72_copy_2__MooTher5") %>%
  # need to remove this partial gene because it was removed to make the other abundance figures and when it is removed, one sample is no longer in the df.
  filter(!geneNum == "Stool_14.k141_240693_1") %>%
  group_by(sample, contig, sample_type, subject, Type) %>%
  summarize(n=n(), median_RPKG=median(RPKG)) %>%
  ungroup() %>%
  group_by(sample, subject, sample_type, Type) %>%
  summarize(sum_RPKG=sum(median_RPKG)) 

plot_RPKG_asr_median <- asr_unique %>%
  group_by(sample, contig, sample_type, subject, Type) %>%
  summarize(n=n(), median_RPKG=median(RPKG)) %>%
  ungroup() %>%
  group_by(sample, subject, sample_type, Type) %>%
  summarize(sum_RPKG=sum(median_RPKG))
```


#box and jitter of both gene clusters
```{r}
# combine asr and dsr data
all_genes <- bind_rows(
  dsr = plot_RPKG_dsr_median,
  asr = plot_RPKG_asr_median,
  .id = "gene_cluster")

# plot a box for each cluster for each type, facet by subject
set.seed(125)
all_genes %>%
  #filter(subject==9) %>%
  ggplot(aes(x = sample_type, y = log10(sum_RPKG), fill = gene_cluster)) +
  geom_boxplot(color = "black",
               position = position_dodge(width = 0.8),
               width = 0.6,
               outlier.shape = NA) +
  # Jitter points with viridis colors
  geom_jitter(aes(color = gene_cluster),
              alpha = 0.8, 
              size = 1.6,
              position = position_jitterdodge(jitter.width = 0.15, jitter.height = 3, dodge.width = 0.8)) +
  scale_color_manual(values = gene_colors, labels = c(expression(italic(asrABC)), expression(italic(dsrAB)))) +
  scale_fill_manual(values = c("transparent", "transparent"), guide = "none") +
  guides(fill = "none") +
  facet_wrap(~ subject, 
             #scales = "free_y",
             strip.position = "top",
             labeller = labeller(subject = function(x) paste("Subject", x))) +
  labs(
    title = expression(paste("Abundances of ", italic(asrABC), " and ", italic(dsrAB), " across sample types and subjects")),
    #subtitle = "Each point represents a sample",
    x = "Sample type",
    #median was taken across a contig to account for subunits
    y = expression("Gene abundance" ~ (log[10]*"RPKG")),
    color = "Gene cluster"
  ) +
  theme_bw() +
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
    )) +
  theme(
    axis.text.x = element_text(size = 14, angle = 60, hjust = 1),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.position = "right",
    legend.text  = element_text(size = 12),
    legend.title = element_text(size = 14),
    strip.placement = "outside",
    strip.background = element_blank(),
    strip.text.x = element_text(size = 12),
    plot.title = element_text(size = 20, hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5))


ggsave(paste0(figureDir, "median_RPKG_asrABC_v_dsrAB.png"),
       width = 11, height = 8, units = "in",   # increase for larger output
       dpi = 600)
```

#ratio plot figure 6B
```{r}
all_genes_subset <- all_genes %>%
  group_by(sample) %>%
  filter(all(c("dsr", "asr") %in% gene_cluster)) %>%
  ungroup()

plot_ratios <- all_genes_subset %>%
  pivot_wider(names_from = gene_cluster, values_from = sum_RPKG) %>%
  mutate(ratio_dsr_asr = dsr/asr) 

summary_stats <- plot_ratios %>%
  group_by(sample_type) %>%
  summarise(median = round(median(ratio_dsr_asr),2),
            n_25pct = round(quantile(ratio_dsr_asr, probs = 0.25),2),
            n_75pct = round(quantile(ratio_dsr_asr, probs = 0.75),2))

log_change <- plot_ratios %>%
  mutate(log_ratio = log2(ratio_dsr_asr)) %>%
  group_by(sample_type) %>%
  summarize(min = min(log_ratio),
            max = max(log_ratio))
  

set.seed(123)
plot_ratios %>%
  ggplot(aes(x = sample_type, y = log2(ratio_dsr_asr))) +
  geom_boxplot(color = "black",
               position = position_dodge(width = 0.8),
               width = 0.6,
               outlier.shape = NA) +
  geom_jitter(aes(color = sample_type),
              alpha = 0.8, 
              size = 3,
              position = position_jitterdodge(jitter.width = 0.15, jitter.height = 3, dodge.width = 0.8)) +
  scale_color_manual(values = sample_type_colors) +
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
    )) +
  labs(
    title = expression(paste("Comparing ", italic(dsrAB), " to ", italic(asrABC), " abundances in the small and large intestines")),
    x = "Sample type",
    y = expression(paste(log[2]*"(", italic(dsrAB), ":", italic(asrABC), ")")),
    color = "Sample type"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(size = 14, angle = 60, hjust = 1),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    legend.position = "right",
    legend.text  = element_text(size = 14),
    legend.title = element_text(size = 14),
    plot.title = element_text(size = 20, hjust = 0.5))

ggsave(paste0(figureDir, "ratio_RPKG_asrABC_v_dsrAB.png"),
       width = 11, height = 8, units = "in",   # increase for larger output
       dpi = 600)
  
```
```{r}
# t test to see if there is a statistically significant difference in the median dsr:asr ratio between capsule and stool samples
median_ratios <- plot_ratios %>%
  group_by(subject, sample_type) %>%
  summarize(median_ratio = median(ratio_dsr_asr))

pp = median_ratios %>% 
  # subjects 1 and 4 don't have dsr in stool
  filter(!subject %in% c(1,4)) %>% 
  dplyr::arrange(sample_type, subject) %>% 
  pivot_wider(id_cols = subject, names_from = sample_type, values_from = median_ratio)

t.test(pp$Capsule, pp$Stool, paired = TRUE)

# cohen's d
# adjust for small sample size
effectsize::cohens_d(
  pp$Capsule,
  pp$Stool,
  data=pp,
  paired = TRUE,
  adjust = TRUE,
  ci = 0.95
)

```
